//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace products.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tclient", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class Tclient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdclientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idclient {
            get {
                return this.IdclientField;
            }
            set {
                if ((this.IdclientField.Equals(value) != true)) {
                    this.IdclientField = value;
                    this.RaisePropertyChanged("Idclient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TProduct", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class TProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Expiration_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdproductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Expiration_date {
            get {
                return this.Expiration_dateField;
            }
            set {
                if ((this.Expiration_dateField.Equals(value) != true)) {
                    this.Expiration_dateField = value;
                    this.RaisePropertyChanged("Expiration_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idproduct {
            get {
                return this.IdproductField;
            }
            set {
                if ((this.IdproductField.Equals(value) != true)) {
                    this.IdproductField = value;
                    this.RaisePropertyChanged("Idproduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tsale", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class Tsale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int client_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] datasaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idsaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long rn_ktkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rn_ktk2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int client_id {
            get {
                return this.client_idField;
            }
            set {
                if ((this.client_idField.Equals(value) != true)) {
                    this.client_idField = value;
                    this.RaisePropertyChanged("client_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] datasale {
            get {
                return this.datasaleField;
            }
            set {
                if ((object.ReferenceEquals(this.datasaleField, value) != true)) {
                    this.datasaleField = value;
                    this.RaisePropertyChanged("datasale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idsale {
            get {
                return this.idsaleField;
            }
            set {
                if ((this.idsaleField.Equals(value) != true)) {
                    this.idsaleField = value;
                    this.RaisePropertyChanged("idsale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long rn_ktk {
            get {
                return this.rn_ktkField;
            }
            set {
                if ((this.rn_ktkField.Equals(value) != true)) {
                    this.rn_ktkField = value;
                    this.RaisePropertyChanged("rn_ktk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rn_ktk2 {
            get {
                return this.rn_ktk2Field;
            }
            set {
                if ((object.ReferenceEquals(this.rn_ktk2Field, value) != true)) {
                    this.rn_ktk2Field = value;
                    this.RaisePropertyChanged("rn_ktk2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        products.ServiceReference1.CompositeType GetDataUsingDataContract(products.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<products.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(products.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertClient", ReplyAction="http://tempuri.org/IService1/insertClientResponse")]
        int insertClient(products.ServiceReference1.Tclient clients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertClient", ReplyAction="http://tempuri.org/IService1/insertClientResponse")]
        System.Threading.Tasks.Task<int> insertClientAsync(products.ServiceReference1.Tclient clients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectClient", ReplyAction="http://tempuri.org/IService1/SelectClientResponse")]
        products.ServiceReference1.Tclient[] SelectClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectClient", ReplyAction="http://tempuri.org/IService1/SelectClientResponse")]
        System.Threading.Tasks.Task<products.ServiceReference1.Tclient[]> SelectClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectproduct", ReplyAction="http://tempuri.org/IService1/SelectproductResponse")]
        products.ServiceReference1.TProduct[] Selectproduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectproduct", ReplyAction="http://tempuri.org/IService1/SelectproductResponse")]
        System.Threading.Tasks.Task<products.ServiceReference1.TProduct[]> SelectproductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectClientAll", ReplyAction="http://tempuri.org/IService1/selectClientAllResponse")]
        products.ServiceReference1.Tclient[] selectClientAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectClientAll", ReplyAction="http://tempuri.org/IService1/selectClientAllResponse")]
        System.Threading.Tasks.Task<products.ServiceReference1.Tclient[]> selectClientAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectSaleAll", ReplyAction="http://tempuri.org/IService1/SelectSaleAllResponse")]
        products.ServiceReference1.Tsale[] SelectSaleAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectSaleAll", ReplyAction="http://tempuri.org/IService1/SelectSaleAllResponse")]
        System.Threading.Tasks.Task<products.ServiceReference1.Tsale[]> SelectSaleAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : products.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<products.ServiceReference1.IService1>, products.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public products.ServiceReference1.CompositeType GetDataUsingDataContract(products.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<products.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(products.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int insertClient(products.ServiceReference1.Tclient clients) {
            return base.Channel.insertClient(clients);
        }
        
        public System.Threading.Tasks.Task<int> insertClientAsync(products.ServiceReference1.Tclient clients) {
            return base.Channel.insertClientAsync(clients);
        }
        
        public products.ServiceReference1.Tclient[] SelectClient() {
            return base.Channel.SelectClient();
        }
        
        public System.Threading.Tasks.Task<products.ServiceReference1.Tclient[]> SelectClientAsync() {
            return base.Channel.SelectClientAsync();
        }
        
        public products.ServiceReference1.TProduct[] Selectproduct() {
            return base.Channel.Selectproduct();
        }
        
        public System.Threading.Tasks.Task<products.ServiceReference1.TProduct[]> SelectproductAsync() {
            return base.Channel.SelectproductAsync();
        }
        
        public products.ServiceReference1.Tclient[] selectClientAll() {
            return base.Channel.selectClientAll();
        }
        
        public System.Threading.Tasks.Task<products.ServiceReference1.Tclient[]> selectClientAllAsync() {
            return base.Channel.selectClientAllAsync();
        }
        
        public products.ServiceReference1.Tsale[] SelectSaleAll() {
            return base.Channel.SelectSaleAll();
        }
        
        public System.Threading.Tasks.Task<products.ServiceReference1.Tsale[]> SelectSaleAllAsync() {
            return base.Channel.SelectSaleAllAsync();
        }
    }
}
